### PR TITLE
kafka integration tests

### LINKED ISSUE #258: [FEA] Create an end-to-end integration test for Kafka
**Is your feature request related to a problem? Please describe.**
We currently don't have tests for the Kafka source and the Kafka sink.

**Describe the solution you'd like**
An end to end validation test that is able to spin up docker containers for Kafka in a similar manner to the way the validation tests spin up a container for Triton.

Ideally it would be good to be able to run these tests as a part of CI.
If we had a Kafka cluster setup for the purposes of CI, tests could theoretically create unique topic names for the purposes of testing.

### LINKED ISSUE #296: [BUG] KafkaSourceStage: input_topic & group_id default values no longer relevant
**Describe the bug**
Current default for `group_id` in both the class and the cli is "custreamz" should be "morpheus"

Current default value for `input_topic` is "test_pcap", this should be a required argument without a default value.

### LINKED ISSUE #309: [BUG] KafkaSourceStage  max_batch_size is ignored
**Describe the bug**
`KafkaSourceStage__Rebalancer::partition_progress_step` declares a `msg_count` variable but never updates it resulting in the while-loop check being useless:
`while (msg_count < m_max_batch_size_fn() && now < batch_end)`

This might actually be intentional as the `FileSourceStage` emits the source data in one big frame regardless of the size, allowing the `DeserializeStage` to slice the output.

**Steps/Code to reproduce bug**
Run `KafkaSourceStage` with a dataset larger than `pipeline_batch_size`, fill the input topic.

**Expected behavior**
Respect the configured max_batch_size

### PR DESCRIPTION
**Pull request by dagardner-nv**
Breaking changes (#296):
* Default `group_id` for `KafkaSourceStage` changes from "custreamz" to "morpheus"
* Remove default topic value for `KafkaSourceStage`.

Other changes:
* Adds Kafka integration tests for ABP, Hammah, Phishing & Sid validation pipelines.
* Uses pytest_kafka to add zookeeper & kafka pytest fixtures
* Configures pytest to only run kafka tests when `--run_kafka` command line flag is set. 
* Adds a `stop_after` argument to `KafkaSourceStage` when defined the source will stop once `stop_after` records have been read from the source.
* Fixes bug in C++ impl preventing KafkaSourceStage from respecting max_batch_size (#309)

Note: Many of the kafka tests are also slower integration tests in effect requiring both the `--run_kafka` & `--run_slow` flags being passed to `pytest`

requires PR #290 
fixes #258
fixes #296
fixes #309

### CODE REVIEW

**Comment by dagardner-nv** [comment]
rerun tests

**Comment by dagardner-nv** [comment]
rerun tests

**Review by mdemoret-nv — APPROVED** [review]
Looks good.

**Comment by mdemoret-nv** [comment]
@gpucibot merge

**Pull request merged**
