### PR TITLE
Adopt MatX v0.4.0

### LINKED ISSUE #909: [FEA]: Adopt MatX v0.4.0
### Is this a new feature, an improvement, or a change to existing functionality?

Change

### How would you describe the priority of this feature request

Low (would be nice)

### Please provide a clear description of problem this feature solves

We're currently tracking a git tag to pick up some fixes which have been rolled into the v0.4.0 release:
https://github.com/NVIDIA/MatX/releases/tag/v0.4.0

### Describe your ideal solution

n/a

### Describe any alternatives you have considered

n/a

### Additional context

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

### PR DESCRIPTION
**Pull request by dagardner-nv**
## Description
* Adopt updated utilities to pick up MatX 0.4.0
* Currently we are tracking a commit hash to adopt fixes needed for Morpheus, which were rolled into the 0.4.0 release.

fixes #909

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by cwharris** [comment]
@cliffburdick has fixed the compilation error, but the PR does not add support for half reduction to pascal architecture.

https://github.com/NVIDIA/MatX/pull/412

**Comment by cliffburdick** [comment]
> @cliffburdick has fixed the compilation error, but the PR does not add support for half reduction to pascal architecture.
> 
> [NVIDIA/MatX#412](https://github.com/NVIDIA/MatX/pull/412)

Please let us know if there's a use case for this on Pascal. Specifically this would be argmax/argmin with fp16/bf16 only I believe.

**Comment by dagardner-nv** [comment]
> > @cliffburdick has fixed the compilation error, but the PR does not add support for half reduction to pascal architecture.
> > [NVIDIA/MatX#412](https://github.com/NVIDIA/MatX/pull/412)
> 
> Please let us know if there's a use case for this on Pascal. Specifically this would be argmax/argmin with fp16/bf16 only I believe.

Thanks for the quick fix! 
We use `matx::rmax`, I'm not sure if that uses argmax or not, but even then we only use `matx::rmax` for 32bit and 64bit floats.

**Comment by dagardner-nv** [comment]
Closing this PR as the goal was to move off of tracking a commit hash on to an official release tag.

**Comment by cliffburdick** [comment]
> > > @cliffburdick has fixed the compilation error, but the PR does not add support for half reduction to pascal architecture.
> > > [NVIDIA/MatX#412](https://github.com/NVIDIA/MatX/pull/412)
> > 
> > 
> > Please let us know if there's a use case for this on Pascal. Specifically this would be argmax/argmin with fp16/bf16 only I believe.
> 
> Thanks for the quick fix! We use `matx::rmax`, I'm not sure if that uses argmax or not, but even then we only use `matx::rmax` for 32bit and 64bit floats.

Those are just max/min and will use cub, so I don't think you're using anything that would be affected.

**Pull request closed without merging**
