### PR TITLE
Model updates and cleanup following upgrade to to triton 24.09

### LINKED ISSUE #2025: [BUG]: Not all models in `models/triton-model-repo` are compatible with Triton 24.09
### Version

24.10

### Which installation method(s) does this occur on?

_No response_

### Describe the bug.

Incompatible models are:
- `phishing-bert-trt` (we're using `phishing-bert-onnx`)
- `ransomw-model-long-rf` (we're using `ransomw-model-short-rf`)
- `ransomw-model-medium-rf` (we're using `ransomw-model-short-rf`)
- `sid-minibert-trt` (we're using `sid-minibert-onnx`)

None of these are used by any of the documented workflows 

### Minimum reproducible example

```bash
docker run --rm -ti --gpus=all -p8000:8000 -p8001:8001 -p8002:8002 \
  nvcr.io/nvidia/morpheus/morpheus-tritonserver-models:24.10 \
  tritonserver --model-repository=/models/triton-model-repo \
    --exit-on-error=false \
    --log-info=true \
    --strict-readiness=false \
    --disable-auto-complete-config
```

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

 [Paste the error here, it will be hidden by default]

</pre></details>

### Full env printout

<details><summary>Click here to see environment details</summary><pre>

 [Paste the results of print_env.sh here, it will be hidden by default]

</pre></details>

### Other/Misc.

_No response_

### Code of Conduct

- [x] I agree to follow Morpheus' Code of Conduct
- [x] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

### PR DESCRIPTION
**Pull request by AnuradhaKaruppiah**
Closes #2025

1. Removed unused models - sid-minibert-trt and phishing-bert-trt
2. Update ransomware-models - ransomw-model-long-rf and ransomw-model-medium-rf with ones regenerated using treelite 4.3

With this change all pretrained models can be loaded - +-------------------------+---------+--------+
| Model                   | Version | Status |
+-------------------------+---------+--------+
| abp-nvsmi-xgb           | 1       | READY  |
| abp-pcap-xgb            | 1       | READY  |
| all-MiniLM-L6-v2        | 1       | READY  |
| log-parsing-onnx        | 1       | READY  |
| phishing-bert-onnx      | 1       | READY  |
| ransomw-model-long-rf   | 1       | READY  |
| ransomw-model-medium-rf | 1       | READY  |
| ransomw-model-short-rf  | 1       | READY  |
| root-cause-binary-onnx  | 1       | READY  |
| sid-minibert-onnx       | 1       | READY  |
+-------------------------+---------+--------+

## Description

Closes 

## By Submitting this PR I confirm:
- I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- When the PR is ready for review, new or existing tests cover these changes.
- When the PR is ready for review, the documentation is up to date with these changes.

### CODE REVIEW

**Comment by dagardner-nv** [comment]
The two README.md files shouldn't be in LFS (is it something in the path?)

**Review by raykallen — APPROVED** [review]

**Pull request merged**
