### PR TITLE
ABP nvsmi sample data generation

### LINKED ISSUE #1097: [DOC]: Add information on how to generate new sample data for the ABP nvsmi example
### How would you describe the priority of this documentation request

Medium

### Describe the future/missing documentation

Without running NetQ, there is no way to generate new sample data for the ABP nvsmi detection example. However, something like the following should allow users to generate new data from a local GPU.

```python
import time

import pandas as pd
from pynvml.smi import NVSMI_QUERY_GPU
from pynvml.smi import nvidia_smi

# Output name
output_file = "nvsmi.json"

# Interval
interval_ms = 1000

query_opts = NVSMI_QUERY_GPU.copy()

# Remove the timestamp and supported clocks from the query
del query_opts["timestamp"]
del query_opts["supported-clocks"]

nvsmi = nvidia_smi.getInstance()

with open(output_file, "w", encoding="UTF-8") as f:

    while (True):

        dq = nvsmi.DeviceQuery(list(query_opts.values()))

        output_dicts = []

        # Flatten the GPUs to allow for a new row per GPU
        for gpu in dq["gpu"]:
            single_gpu = dq.copy()

            # overwrite the gpu list with a single gpu
            single_gpu["gpu"] = gpu

            output_dicts.append(single_gpu)

        df = pd.json_normalize(output_dicts, record_prefix="nvidia_smi_log")

        # Rename the id column to match the XML converted output from NetQ
        df.rename(columns={"gpu.id": "gpu.@id", "count": "attached_gpus"}, inplace=True)

        df.rename(columns=lambda x: "nvidia_smi_log" + "." + x, inplace=True)

        # Add the current timestamp
        df.insert(0, "timestamp", time.time())

        df.to_json(f, orient="records", lines=True)

        f.flush()

        time.sleep(interval_ms / 1000.0)
```

This should be included in the documentation to make it clearer for the user how to run their own data through the example.

### Where have you looked?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

### PR DESCRIPTION
**Pull request by efajardo-nv**
## Description
- Add script to ABP nvsmi example for generating sample data
- Data generated using script does not contain all the columns used to train the current nvsmi model. Retrain the model using the 18 overlapping columns.
- Update model, model config, training notebook/script, feature columns file
- Update README with instructions on how to run script

Closes #1097 

## Checklist
[x] I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
[x] New or existing tests cover these changes.
[x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by efajardo-nv** [comment]
The dataset generated using the script contains 18 of the 29 columns used to train model. Therefore, example inference pipeline will fail because of the missing columns. These are the 18 columns:

```
['nvidia_smi_log.gpu.fb_memory_usage.used',
 'nvidia_smi_log.gpu.fb_memory_usage.free',
 'nvidia_smi_log.gpu.utilization.gpu_util',
 'nvidia_smi_log.gpu.utilization.memory_util',
 'nvidia_smi_log.gpu.temperature.gpu_temp',
 'nvidia_smi_log.gpu.temperature.gpu_temp_max_threshold',
 'nvidia_smi_log.gpu.temperature.gpu_temp_slow_threshold',
 'nvidia_smi_log.gpu.power_readings.power_draw',
 'nvidia_smi_log.gpu.clocks.graphics_clock',
 'nvidia_smi_log.gpu.clocks.sm_clock',
 'nvidia_smi_log.gpu.clocks.mem_clock',
 'nvidia_smi_log.gpu.applications_clocks.graphics_clock',
 'nvidia_smi_log.gpu.applications_clocks.mem_clock',
 'nvidia_smi_log.gpu.default_applications_clocks.graphics_clock',
 'nvidia_smi_log.gpu.default_applications_clocks.mem_clock',
 'nvidia_smi_log.gpu.max_clocks.graphics_clock',
 'nvidia_smi_log.gpu.max_clocks.sm_clock',
 'nvidia_smi_log.gpu.max_clocks.mem_clock']
```

Tried retraining model with just the 18 columns using:
https://github.com/nv-morpheus/Morpheus/blob/branch-23.11/models/training-tuning-scripts/abp-models/abp-nvsmi-xgb-20210310.ipynb. 

Accuracy was still 100%. Deployed new model to Triton. Ran the inference pipeline against the new model using he dataset generated from the script. Pipeline ran all the way through with no errors.

@gbatmaz would it be possible to use model trained on the 18 columns instead so that datasets from both `NetQ` and the script (`pyNVML/nvidia-smi`) can be used for the pipeline?

**Comment by mdemoret-nv** [comment]
@efajardo-nv I believe that this isnt specific to NetQ, but is more specific to the GPU you are using. Have you run the script on a different GPU (quadro vs geforce vs tesla). Some may not have the necessary means of monitoring

**Comment by efajardo-nv** [comment]
> @efajardo-nv I believe that this isnt specific to NetQ, but is more specific to the GPU you are using. Have you run the script on a different GPU (quadro vs geforce vs tesla). Some may not have the necessary means of monitoring

@mdemoret-nv Yes, that's correct. The columns generated from the script are slightly different between Tesla V100 (126 columns) and Quadro RTX 8000 (124 columns) but both have same 18 columns that overlap with:
https://github.com/nv-morpheus/Morpheus/blob/branch-23.11/models/data/columns_fil.txt

**Comment by gbatmaz** [comment]
> The dataset generated using the script contains 18 of the 29 columns used to train model. Therefore, example inference pipeline will fail because of the missing columns. These are the 18 columns:
> 
> ```
> ['nvidia_smi_log.gpu.fb_memory_usage.used',
>  'nvidia_smi_log.gpu.fb_memory_usage.free',
>  'nvidia_smi_log.gpu.utilization.gpu_util',
>  'nvidia_smi_log.gpu.utilization.memory_util',
>  'nvidia_smi_log.gpu.temperature.gpu_temp',
>  'nvidia_smi_log.gpu.temperature.gpu_temp_max_threshold',
>  'nvidia_smi_log.gpu.temperature.gpu_temp_slow_threshold',
>  'nvidia_smi_log.gpu.power_readings.power_draw',
>  'nvidia_smi_log.gpu.clocks.graphics_clock',
>  'nvidia_smi_log.gpu.clocks.sm_clock',
>  'nvidia_smi_log.gpu.clocks.mem_clock',
>  'nvidia_smi_log.gpu.applications_clocks.graphics_clock',
>  'nvidia_smi_log.gpu.applications_clocks.mem_clock',
>  'nvidia_smi_log.gpu.default_applications_clocks.graphics_clock',
>  'nvidia_smi_log.gpu.default_applications_clocks.mem_clock',
>  'nvidia_smi_log.gpu.max_clocks.graphics_clock',
>  'nvidia_smi_log.gpu.max_clocks.sm_clock',
>  'nvidia_smi_log.gpu.max_clocks.mem_clock']
> ```
> 
> Tried retraining model with just the 18 columns using: https://github.com/nv-morpheus/Morpheus/blob/branch-23.11/models/training-tuning-scripts/abp-models/abp-nvsmi-xgb-20210310.ipynb.
> 
> Accuracy was still 100%. Deployed new model to Triton. Ran the inference pipeline against the new model using the dataset generated from the script. Pipeline ran all the way through with no errors.
> 
> @gbatmaz would it be possible to use model trained on the 18 columns instead so that datasets from both `NetQ` and the script (`pyNVML/nvidia-smi`) can be used for the pipeline?

Yes, it should be okay for them to modify and use whatever is available for the notebook since you've done the sanity check. For production, it's probably a better idea to retrain with their own data to make sure correct distinction can be done with their type of workloads.

**Comment by mdemoret-nv** [comment]
@efajardo-nv Is this still a draft?

**Comment by efajardo-nv** [comment]
@mdemoret-nv i need to retrain the model using the 18 columns in order for pipeline to work using inference data generated from the script. should be okay according to @gbatmaz. i can do that now unless you see any issues with that.

**Review by mdemoret-nv — APPROVED** [review]

**Review by gbatmaz — APPROVED** [review]
LGTM

**Pull request merged**
