### PR TITLE
Root cause analysis datasets

### PR DESCRIPTION
**Pull request by efajardo-nv**
- Add training data used by root cause analysis training script and notebook
- Replace existing CSV validation data file with JSON lines
- Update root cause pipeline command in README to read and output JSON lines

Unblocks #452

### CODE REVIEW

**Review by raykallen — APPROVED** [review]
I checked all data files. They correctly match the small anonymized kernel logs to be shared publicly.

**Review by mdemoret-nv — COMMENTED** [review]
> Replace existing CSV validation data file with JSON lines

Whats the reason for converting from CSV to JSON lines? CSV generally works much better with Morpheus as it's easier to parse and C++ accelerated.

**Comment by efajardo-nv** [comment]
@mdemoret-nv we decided to switch to jsonlines for consistency since it's also used in phishing and sid-nlp as well as @gbatmaz's root cause validation script.

**Review by mdemoret-nv — APPROVED** [review]

**Comment by raykallen** [comment]
@gpucibot merge

**Pull request merged**
