### PR TITLE
Fixing compilation with SRF 22.08a

### PR DESCRIPTION
**Pull request by mdemoret-nv**
When compiling with SRF 22.08 conda package, some modifications are necessary to get the compilation to succeed.

### CODE REVIEW

**Review by dagardner-nv — APPROVED** [review]
LGTM

**Comment by mdemoret-nv** [comment]
rerun tests

**Comment by mdemoret-nv** [comment]
rerun tests

**Comment by mdemoret-nv** [comment]
rerun tests

**Review by BartleyR — APPROVED** [review]

**Pull request merged**
