### PR TITLE
Move data dir to models

### LINKED ISSUE #1100: [BUG]: CI failing with ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/opt/conda/envs/morpheus/lib/python3.10/site-packages/fastjsonschema-2.17.1.dist-info/METADATA'
### Version

23.07

### Which installation method(s) does this occur on?

Docker

### Describe the bug.

CI is failing in the test stage with:
```
Pip subprocess error:
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/opt/conda/envs/morpheus/lib/python3.10/site-packages/fastjsonschema-2.17.1.dist-info/METADATA'


failed

CondaEnvException: Pip failed
```

### Minimum reproducible example

```shell
Open a PR
```

### Relevant log output

_No response_

### Full env printout

_No response_

### Other/Misc.

_No response_

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

### PR DESCRIPTION
**Pull request by dagardner-nv**
## Description
* Move `morpheus/data` to `models/data`
* Replace `morpheus/data` with a symlink to `models/data`
* Newly built CI images to fix #1100 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by mdemoret-nv — APPROVED** [review]
Lets wait for confirmation from packaging that this looks good before merging

**Comment by pdmack** [comment]
@mdemoret-nv @dagardner-nv does this look right?
Trying to understand the change.
```
-rw-rw-r-- 1 root root 755468 Jul 25 00:47 /opt/conda/envs/morpheus/lib/python3.10/site-packages/morpheus/data/bert-base-cased-hash.txt
-rw-rw-r-- 1 root root 213450 Jul 25 00:47 /opt/conda/envs/morpheus/lib/python3.10/site-packages/morpheus/data/bert-base-cased-vocab.txt
-rw-rw-r-- 1 root root 796289 Jul 25 00:47 /opt/conda/envs/morpheus/lib/python3.10/site-packages/morpheus/data/bert-base-uncased-hash.txt
-rw-rw-r-- 1 root root 231508 Jul 25 00:47 /opt/conda/envs/morpheus/lib/python3.10/site-packages/morpheus/data/bert-base-uncased-vocab.txt
-rw-rw-r-- 1 root root 755468 Jul 25 00:39 /workspace/models/data/bert-base-cased-hash.txt
-rw-rw-r-- 1 root root 213450 Jul 25 00:39 /workspace/models/data/bert-base-cased-vocab.txt
-rw-rw-r-- 1 root root 796289 Jul 25 00:39 /workspace/models/data/bert-base-uncased-hash.txt
-rw-rw-r-- 1 root root 231508 Jul 25 00:39 /workspace/models/data/bert-base-uncased-vocab.txt
lrwxrwxrwx 1 root root     38 Jul 25 00:39 /workspace/models/training-tuning-scripts/log-parsing-models/resources/bert-base-cased-hash.txt -> ../../../data/bert-base-cased-hash.txt
lrwxrwxrwx 1 root root     38 Jul 25 00:39 /workspace/models/training-tuning-scripts/sid-models/resources/bert-base-cased-hash.txt -> ../../../data/bert-base-cased-hash.txt
lrwxrwxrwx 1 root root     39 Jul 25 00:39 /workspace/models/training-tuning-scripts/sid-models/resources/bert-base-cased-vocab.txt -> ../../../data/bert-base-cased-vocab.txt
lrwxrwxrwx 1 root root     40 Jul 25 00:39 /workspace/models/training-tuning-scripts/sid-models/resources/bert-base-uncased-hash.txt -> ../../../data/bert-base-uncased-hash.txt
lrwxrwxrwx 1 root root     41 Jul 25 00:39 /workspace/models/training-tuning-scripts/sid-models/resources/bert-base-uncased-vocab.txt -> ../../../data/bert-base-uncased-vocab.txt
```

**Comment by dagardner-nv** [comment]
@pdmack we moved the data dir to `models/data` and replaced it with a symlink such that in the source tree you have: `morpheus/data -> ../models/data` 
Then we updated the symlinks under the `models/training-tuning-scripts` dir.

When we perform an install setuptools follows the symlink and copies the actual files into site-packages.

What you are seeing is that if you use the `docker/run_container_release.sh` script it mounts the source tree's `models` dir over the images dir:
```
-v $PWD/models:/workspace/models
```

@mdemoret-nv and I talked about this and we wanted to come up with something that would work for both users in a bare-metal install, a local docker build or a container downloaded from NGC.

**Review by mdemoret-nv — APPROVED** [review]
Looks good.

**Pull request merged**
