### PR TITLE
[REVIEW] updating the filenames in the paths and adding the missing file for abp

### LINKED ISSUE #384: [BUG] update the dataset paths in the training notebooks and add training data for ABP
**Describe the bug**
Fix the paths of the fine-tuning/training notebooks

**Expected behavior**
training notebooks should be able to find the data in the repo

### PR DESCRIPTION
**Pull request by gbatmaz**
updating the training filename in the path in the dfp notebook
closes #384

### CODE REVIEW

**Review by drobison00 — APPROVED** [review]
Looks fine; assuming all the appropriate LFS paths are updated?

**Comment by BartleyR** [comment]
rerun tests

**Comment by raykallen** [comment]
@gbatmaz this PR is failing flake8 style-check. Can you fix?

**Comment by raykallen** [comment]
@gpucibot merge

**Pull request merged**
