### PR TITLE
Final cleanup for 23.01 release

### PR DESCRIPTION
**Pull request by mdemoret-nv**
Includes various fixes for the following:

1. Fixing copyright headers
2. Fixing python style checks which were missing file exclusions
3. Fixing python style
4. Fixing cpp style
5. Fixing release container build

### CODE REVIEW

**Review by drobison00 — APPROVED** [review]
LGTM

**Review by dagardner-nv — APPROVED** [review]

**Review by BartleyR — APPROVED** [review]

**Review by tzemicheal — APPROVED** [review]
The DS docs LGTM!

**Review by raykallen — APPROVED** [review]
lgtm

**Review by bsuryadevara — APPROVED** [review]
LGTM

**Pull request merged**
