### PR TITLE
Digital Fingerprinting 2.0 Pipelines

### LINKED ISSUE #207: [FEA] Digital Fingerprinting Updates for Feature Engineering
### Features currently used in Azure models

1- **appDisplayName** : i.e. Windows sign in, MS Teams, Office 365
2 - **riskEventTypesv2** : AzureADThreatIntel, unfamiliarFeatures
3 - **locationcity**: City name
4 - **clientAppUsed** i.e. IMAP4, Browser
5 - **deviceDetaildisplayName** : i.e. username-LT
6 - **deviceDetailbrowser** : i.e. EDGE 98.0.xyz Chrome 98.0.xyz
7 - **deviceDetailoperatingSystem** i.e. Linux, IOS 15, Windows 10
8 - **statusfailureReason**: i.e. external security challenge not satisfied, error validating credentials
9 - **locationcountryOrRegion**: Country or Region name

Derived features:

10 - **locincrement** - This feature increments every time the logs contain a distinct city within that day. It tracks the cities mentioned in the locationcity feature.
11 - **logcount** - This feature tracks the number of logs generated by a user within that day. It increments with every log
12 - **appincrement** - This feature increments every time the logs contain a distinct app in the appDisplayName field within that day

### Features currently used in DUO models

1 - **accessdevicebrowser**: i.e. Edge, Chrome, Chrome Mobile
2 - **accessdeviceos** i.e. Android, Windows
3 - **device**: phone number
4 - **result**: SUCCESS or FAILURE 
5 - **browsersbrowserfamily** : Edge, Edge Chromium, Chrome
6 - **reason**: Reason for the results. i.e. User Cancelled, User Approved, User Mistake, No Response
7 - **locationcity** : City name

*Derived features
8 - **Locincrement**: This feature increments every time a log contains a distinct city within that day. It tracks the cities mentioned in the location country+city feature.
9 - **Logcount**: This feature tracks the number of logs generated by a user within that day. It increments with every log.

### LINKED ISSUE #208: [FEA] Digital Fingerprinting Pipeline Updates for new DS Features
1. An anomaly score is calculated every time a new log becomes available
2. The derived features are updated every time a new log becomes available
3. We will train models for each user with all the data. We will then run inference with the training data only to save the mean of the reconstruction loss and the standard deviation of the reconstruction loss for that user and store it. This value will be used in inference. Every time there’s a new reconstruction loss, we calculate a z-score with that stored mean and std. This result will give the anomaly metric we use for each log. Some of the features will be used as they are. Some features will be derived from the logs or other columns.
4. Features will be scaled with the standard scaler.
5. For each user, logs are used in the order they are generated for the sanity of the derived features’ impact.
6. If the inference has to be run in batches (instead of real-time streaming), we need to make sure the derived features have already been updated for each user for every log before they are used.
7. Users should be able to use two thresholds for DUO and two thresholds for Azure logs.
8. When the lower threshold** is exceeded(potentially due to non-actionable True positives) the SOC team or analysts can choose to trigger retraining for that user automatically.
9. When the higher threshold*** is exceeded SOC team can choose to investigate for potential actionable True Positives.
10. As an alternative, the users can monitor the top K**** anomalies in a rolling window. Past hour or past 24 hours***** etc.
11. For new joiners, a generic model should be trained for that manager or org, and until the user accumulates a number of logs******, they keep using the generic/aggregate model
12. Granularity should be customisable.

### LINKED ISSUE #339: [FEA] Migrate `DFEncoder` For into `nv-morpheus` Org
**Is your feature request related to a problem? Please describe.**
Currently, the `DFEncoder` changes are hosted in a personal fork here: https://github.com/efajardo-nv/dfencoder. We should move this under the `nv-morpheus` org.

**Describe the solution you'd like**
Move https://github.com/efajardo-nv/dfencoder to `nv-morpheus/dfencoder`. Update the existing uses of that repo in Morpheus to the new location.

### PR DESCRIPTION
**Pull request by efajardo-nv**
- Update existing HAMMAH pipeline to [new DFP 2.0 requirements](https://github.com/nv-morpheus/Morpheus/issues/208).
- Add source stages for Azure and Duo.
- Add Azure and Duo DFP pipelines to Morpheus CLI.
- Example on how to run CloudTrail DFP pipeline using Python API.
- Add options to save trained user models to file and load later for inference-only workflow.
- Make AE source stages extensible to allow for deriving new features.
- Derived features for Azure and Duo logs. See #207
- Option to use generic model for user who don't have enough training data
- Add README with information about environment setup and running DFP pipelines.
- ~Update `dfencoder` dependency to [new branch](https://github.com/efajardo-nv/dfencoder/tree/morpheus-22.08) which includes breaking changes.~ Updated `dfencoder` branch to not break current/previous Morpheus versions. Can now be merged into `nv-updates`.
- Update HAMMAH validation scripts

Closes #207 
Closes #208
Closes #339

### CODE REVIEW

**Review by gbatmaz — APPROVED** [review]
LGTM

**Comment by efajardo-nv** [comment]
rerun tests

**Review by mdemoret-nv — APPROVED** [review]
This is in a good enough state to start building off of it with the other PRs that need to go in and can be worked in parallel

**Comment by mdemoret-nv** [comment]
@gpucibot merge

**Pull request merged**
