### PR TITLE
Update dfp-model-card.md

### PR DESCRIPTION
**Pull request by HesAnEasyCoder**
Updating per Model Card++ 3.0 Release.

## Description

Closes 

## By Submitting this PR I confirm:
- I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- When the PR is ready for review, new or existing tests cover these changes.
- When the PR is ready for review, the documentation is up to date with these changes.

### CODE REVIEW

**Comment by HesAnEasyCoder** [comment]
Hey Devin!  Can you get this merged so I can get this approved?

**Comment by mdemoret-nv** [comment]
@HesAnEasyCoder Can you update your PR to target the current development branch: `branch-24.06`? Then we can run CI and get this merged.

**Comment by HesAnEasyCoder** [comment]
Done!

**Review by mdemoret-nv — APPROVED** [review]

**Pull request merged**
