### PR TITLE
[morpheus-refactor] Move morpheus source to python/morpheus

### PR DESCRIPTION
**Pull request by AnuradhaKaruppiah**
## Description
This is the first PR to update the source layout. It moves the morpheus source code to a new sub-tree that will allow breaking out morpheus functional blocks from the morpheus-base -
```
.
|___ CMakeLists.txt
|___ python
|    |___ CMakeLists.txt
|    |___ morpheus
|    |    |___ CMakeLists.txt
|    |    |___ setup.py
|    |    |___ setup.cfg
|    |    |___ MANIFEST.in
|    |    |___ morpheus
|    |    |    |___ __init__.py
|    |    |    |___ _lib
|    |    |    |___ etc.
|    |___ morpheus_N
```

## By Submitting this PR I confirm:
- I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- When the PR is ready for review, new or existing tests cover these changes.
- When the PR is ready for review, the documentation is up to date with these changes.

### CODE REVIEW

**Review by dagardner-nv — APPROVED** [review]
LGTM, my main question is, are in-place python installs still supported? How does it work?

**Review by cwharris — APPROVED** [review]
lgtm

**Comment by AnuradhaKaruppiah** [comment]
> LGTM, my main question is, are in-place python installs still supported? How does it work?

That is a  good question. The install is per-functional block. For eg. if you were setting up a dev env it would look something like this -
```
cd $MORPHEUS_ROOT
pip install -e python/morpheus
pip install -e python/morpheus_N  # hypothetical functional block
```

**Pull request merged**
