### PR TITLE
Fix early stopping code in dfencoder to use average loss of batches in validation set

### LINKED ISSUE #905: [BUG]: dfencoder early stopping code using last batch's loss instead of average loss of the epoch
### Version

23.03

### Which installation method(s) does this occur on?

_No response_

### Describe the bug.

The current implementation of early stopping code in dfencoder is using the net loss of the last batch of the validation set to evaluate when to early-stop. This approach can be problematic as the last batch of the validation set may contain a small number of data points, which may not be representative of the entire validation set. 
It is recommended to use the average loss of all batches in the validation set to evaluate the early stopping criteria, as this approach will be more objective and representative of the entire dataset. 
The bug should be fixed by updating the early stopping code to use the average loss of the batches in the validation set.

### Minimum reproducible example

_No response_

### Relevant log output

_No response_

### Full env printout

_No response_

### Other/Misc.

_No response_

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

### PR DESCRIPTION
**Pull request by hsin-c**
## Description
This PR fixes the early stopping code in dfencoder to use the average loss of all batches in the validation set, instead of just the net loss of the last batch. This change will ensure that the early stopping criteria are more representative of the entire validation set, rather than relying on a potentially unrepresentative subset of the data.

closes #905 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by mdemoret-nv — CHANGES_REQUESTED** [review]
Can you add a test that verifies if early stopping is working correctly?

**Comment by hsin-c** [comment]
> Can you add a test that verifies if early stopping is working correctly?

Added testing for early stopping. (Providing coverage for the early-stopping code in general, not testing the change in this PR specifically as it's a logic update on the data science side).

**Review by mdemoret-nv — APPROVED** [review]
Thanks for adding that test

**Pull request merged**
