### PR TITLE
Ransomware models need update for Triton 22.08

### PR DESCRIPTION
**Pull request by bsuryadevara**
Updated treelite version for ransomware models from 2.3.0 to 2.4.0 to support Trition 22.08

### CODE REVIEW

**Comment by pdmack** [comment]
LGTM
```
+-------------------------+---------+--------+
| Model                   | Version | Status |
+-------------------------+---------+--------+
| abp-nvsmi-xgb           | 1       | READY  |
| log-parsing-onnx        | 1       | READY  |
| phishing-bert-onnx      | 1       | READY  |
| ransomw-model-long-rf   | 1       | READY  |
| ransomw-model-medium-rf | 1       | READY  |
| ransomw-model-short-rf  | 1       | READY  |
| sid-minibert-onnx       | 1       | READY  |
+-------------------------+---------+--------+
```

**Review by pdmack — APPROVED** [review]
LGTM

**Review by efajardo-nv — APPROVED** [review]

**Comment by BartleyR** [comment]
@gpucibot merge

**Pull request merged**
