### PR TITLE
Create action to add issues/prs to the project

### PR DESCRIPTION
**Pull request by jarmak-nv**
Uses GitHub Actions to automatically add issues and PRs to our tracking project.

### CODE REVIEW

**Comment by mdemoret-nv** [comment]
rerun tests

**Review by mdemoret-nv — APPROVED** [review]
Looks good. Not sure why CI is failing

**Comment by jarmak-nv** [comment]
Saw some error about a copyright header on the last run, will be interesting if the same error appears.

**Comment by mdemoret-nv** [comment]
rerun tests

**Comment by mdemoret-nv** [comment]
rerun tests

**Comment by mdemoret-nv** [comment]
@gpucibot merge

**Pull request merged**
